- client/.eslintrc.json
- client/components/GNB/Logo.tsx
- client/components/GNB/Menu.tsx
- client/components/GNB/UserInfo.tsx
- client/components/GNB/index.tsx
- client/next.config.js
- client/pages/_app.tsx
- client/pages/api/user/login-status.ts
- https://github.com/boostcampwm-2022/web12-MOJ/issues/5
- 위 이슈에서 github OAuth를 제외한 나머지 진행
- global css 적용
- GNB 컴포넌트 작성
- React strict 모드 해제, eslint 수정
- bable 관련 오류 수정
-  https://github.com/boostcampwm-2022/web12-MOJ/issues/6
- 로그인 상태 mock API 구현
-  https://github.com/boostcampwm-2022/web12-MOJ/issues/15
-  https://github.com/boostcampwm-2022/web12-MOJ/issues/16
-  https://github.com/boostcampwm-2022/web12-MOJ/issues/14
- GNB 적용
> 1 공통 - 상단(GNB) #5

- client/axios.ts
- client/components/paginator.tsx
- client/components/problemList.tsx
- client/components/problemListRow.tsx
- client/pages/_app.tsx
- client/pages/api/problem.tsx
- client/pages/index.tsx
- https://github.com/boostcampwm-2022/web12-MOJ/issues/8
- [검색(문제 번호 및 문제 제목) 시에 필터링된 문제 리스트를 제공, 역순 정렬] 제외한 나머지 진행
- https://github.com/boostcampwm-2022/web12-MOJ/issues/24
- list 스타일 수정
- https://github.com/boostcampwm-2022/web12-MOJ/issues/30
- https://github.com/boostcampwm-2022/web12-MOJ/issues/33
- mock api 작성
- https://github.com/boostcampwm-2022/web12-MOJ/issues/34
- https://github.com/boostcampwm-2022/web12-MOJ/issues/35
> 2. 문제 목록 (#8)

- deploy.sh
> build: deploy.sh 수정

- client/components/status/StatusList.tsx
- client/pages/api/submissions/[id].ts
- client/pages/status/[id].tsx
- https://github.com/boostcampwm-2022/web12-MOJ/issues/11
- https://github.com/boostcampwm-2022/web12-MOJ/issues/17
- list component로 생성
- https://github.com/boostcampwm-2022/web12-MOJ/issues/19
- https://github.com/boostcampwm-2022/web12-MOJ/issues/20
- 풀이 상세 mock api 생성
> Feat/#11 (close #11)

- client/components/List/list.tsx
- client/components/List/listRow.tsx
- client/components/svgs/close.tsx
- client/components/svgs/index.tsx
- client/mock/problems.ts
- client/pages/api/problems/[id].ts
- client/pages/api/problems/[id]/visible.ts
- client/pages/api/problems/index.ts
- client/pages/my-problem/index.tsx
- https://github.com/boostcampwm-2022/web12-MOJ/issues/9
- mock 데이터 추가, API 수정 및 추가
- 문제 삭제 모달
- 문제 공개 여부 토글
> 6. 문제 출제 (#9) [추가 변경사항]

- server/.gitignore
- server/package.json
- server/src/app.module.ts
- server/src/problems/entities/example.entity.ts
- server/src/problems/entities/problem.entity.ts
- server/src/problems/entities/testcase.entity.ts
- server/src/problems/problems.module.ts
- server/src/submissions/entities/language.entity.ts
- server/src/submissions/entities/result.entity.ts
- server/src/submissions/entities/state.entity.ts
- server/src/submissions/entities/submission.entity.ts
- server/src/submissions/submissions.module.ts
- server/src/users/entities/user.entity.ts
- server/src/users/users.module.ts
- server/yarn.lock
- #78 
- typeorm 설치
- nest config 설정
- naming strategies 설정
- 쿼리 로깅 설정
- 엔티티 작성
> Feat/#78 (Close #78)

- client/components/GNB/UserInfo.tsx
- client/components/GNB/index.tsx
- client/next.config.js
- client/pages/users/oauth.tsx
- server/src/users/users.controller.ts
- server/src/users/users.service.ts
- #87 
- GET /api/users/login-status 구현
- POST /api/users/logout 구현
- API rewrites 수정
> 2. POST /github-login (Close #87)

- server/src/main.ts
- server/src/users/dtos/github-login.dto.ts
- server/src/users/users.controller.ts
- server/src/users/users.service.ts
- #99 
- DTO를 이용해 입력값 검증
- 세션 쿠키 max age 설정
> Refactor (Close #99)

- client/components/Problem/ProblemContainer.tsx
- client/global.d.ts
- client/pages/my-problem/edit/[id].tsx
- client/pages/problem/[id].tsx
- server/src/main.ts
- server/src/problems/entities/problem.entity.ts
- server/src/problems/problems.controller.ts
- server/src/problems/problems.service.ts
> 5. GET /api/problems/:id (close #83)

- client/pages/my-problem/new.tsx
- server/src/problems/entities/problem.entity.ts
- server/src/problems/problems.controller.ts
- server/src/problems/problems.service.ts
- #102 
- 문제 만들 때 출제자 추가
- 400, 401 에러 핸들링
> 3. POST /api/problems 출제자 추가 (close #102)

- client/pages/my-problem/tc/[id].tsx
- server/src/main.ts
- server/src/problems/dtos/get-testcase.dto.ts
- server/src/problems/entities/problem.entity.ts
- server/src/problems/problems.controller.ts
- server/src/problems/problems.service.ts
- #89 
- #108
- GET /api/problems/:id/tc 구현
- 400, 401, 403, 404 예외처리
- FE API 연결
> 8. GET /problems/:id/tc (Close #89)

- client/pages/my-problem/tc/[id].tsx
- server/src/main.ts
- server/src/problems/dtos/get-testcase.dto.ts
- server/src/problems/dtos/post-testcase.dto.ts
- server/src/problems/problems.controller.ts
- server/src/problems/problems.service.ts
- #90 
- #111 
- 암시적 형변환 제거
- POST /problems/:id/tc API 생성 및 FE 적용
> 9. POST /problems/:id/tc (close #90 close #111)

- server/src/problems/entities/problem.entity.ts
- server/src/problems/problems.controller.ts
- server/src/problems/problems.service.ts
- #85 
- Problem Entity soft delete 컬럼 추가
- DELETE /api/problems/:id 구현
- soft delete
> feat: Close #85

- client/global.d.ts
- client/pages/my-problem/edit/[id].tsx
- #126 
- 임시 방편으로 두가지 이름을 전부 사용하기 위해 옵셔널로 설정해 두가지 모두 채택했습니다.
- 추후 리팩토링이 필요합니다.
- put을 patch로 수정한 내용이 적용되지 않아 다시 수정
> 병합 이후 생긴 오류 수정

- server/src/problems/problems.service.ts
- #129
- 자신의 문제에만 제출 할 수 있는 버그 수정
> fix: 문제 제출 권한 문제 해결 (Close #129)

- server/src/submissions/submissions.service.ts
- #167 
* 페이지네이션 쿼리문 limit, offset으로 변경
- left join 쓸 때는 skip, take 대신에 limit, offset을 써야함.
> 페이지네이션 쿼리문 limit, offset으로 변경

- scoring-server/src/queue/queue.module.ts
- server/src/problems/problems.module.ts
- #173 
* redis host, port, password 환경변수로 분리
> fix: redis 연결 환경변수 분리(#173)

- client/components/Problem/ProblemContainer.tsx
- client/pages/my-problem/edit/[id].tsx
- client/pages/my-problem/index.tsx
- client/pages/my-problem/new.tsx
- client/pages/my-problem/tc/[id].tsx
- client/pages/problem/[id].tsx
- client/pages/status/[id].tsx
- client/pages/status/index.tsx
- server/src/problems/dtos/create-problem.dto.ts
- server/src/problems/dtos/post-testcase.dto.ts
- server/src/problems/dtos/update-problem.dto.ts
- server/src/problems/problems.service.ts
- #149 
- #156 
- #176 
- #149 
- 각 페이지별로 알맞는 타이틀을 설정함.
- #156 
- `IsNotEmpty` -> `IsDefined`로 DTO 검증 변경
- 테스트 케이스 output은 빈칸 허용 안되도록 `IsNotEmpty` 추가
- 클라이언트 테스트케이스 빈칸 허용하도록 검증 제외
- #176 
- `div` 태그에 바로 입출력 예제를 넣으려해서 발생
- `pre`태그로 변경하여 해결
- 내용을 적어주세요.
> 입출력 예제 줄바꿈, 테케 및 예제 input 빈칸 허용하도록 수정 및 페이지별 타이틀 변경

- scoring-server/src/queue/queue.consumer.ts
- #183
- MyPromise 선언
- Promise 상속
- 필요없는 console.log 제거
- interfece로 정의된 MyPromise를 상속을 통해 Promise의 subclass로 변경
> refactor: 채점 서버 큐 (Close #183)

- client/components/Problem/ProblemContainer.tsx
- client/components/problemList.tsx
- client/global.d.ts
- client/package.json
- client/pages/index.tsx
- client/pages/status/[id].tsx
- client/pages/status/index.tsx
- client/yarn.lock
- server/src/problems/problems.service.ts
- server/src/submissions/submissions.controller.ts
- server/src/submissions/submissions.service.ts
- #187 
- #188 
- #189 
- #190
> 기능 개발 및 버그 수정

- client/components/GNB/Logo.tsx
- client/components/GNB/index.tsx
- client/components/Problem/ProblemContainer.tsx
- client/pages/_app.tsx
- client/pages/_document.tsx
- client/styles/style.ts
- #194
- #195
- font family 변경
- 나눔 스퀘어
- 나눔 스퀘어 네오(로고)
- GNB 상단 고정
> 12.13 프론트 작업 (Close #196)

- client/pages/my-problem/tc/[id].tsx
- server/src/problems/problems.controller.ts
- server/src/problems/problems.service.ts
- #211 
- 테스트 케이스 50개 초과해서 넣을 경우 Bad Request 에러 발생
- 에러 메시지 프론트에서 보여줌
- 스로틀 설정 수정
> 테스트 케이스 50개 제한

- README.md
- server/src/problems/throttler-behind-proxy.guard.ts
- #214 
- ip 주소를 이용해서 요청 횟수 제한을 걸면 next가 nest를 호출하는 방식으로 작성된 서버에서는 정상적으로 동작하지 않았습니다. 그래서 ip 주소가 아니라 세션을 사용해 요청한 사람을 확인했습니다.
> 22.12.15 hotfix

- scoring-server/src/scoring/scoring.service.ts
> fix: 채점 중간에 오류날 때 임시 파일 제거하도록 수정 (Close #217)

- client/components/GNB/UserInfo.tsx
- client/components/List/list.tsx
- client/components/List/listRow.tsx
- client/components/List/paginator.tsx
- client/components/Modal/DeleteProblemModal.tsx
- client/components/common/IOList/InputContainer.tsx
- client/components/common/IOList/Row.tsx
- client/components/paginator.tsx
- client/components/problemList.tsx
- client/pages/index.tsx
- client/pages/my-problem/new.tsx
- scoring-server/python/run.py
- scoring-server/src/scoring/scoring.service.ts
- server/src/problems/problems.service.ts
- server/src/problems/throttler-behind-proxy.guard.ts
- #179 
- 사용하지 않는 변수 제거
- 사용하지 않는 import 제거
> refactor: 사용하지 않는 변수, import 제거 (Close #179)

- client/pages/my-problem/new.tsx
- #208
- 문제 추가 페이지에서 시간 제한을 넘겨 설정하면 "입력 형식 및 빈 칸이 없는지 확인하세요." 라고 뜹니다.
- 400 status가 오면 무조건 같은 메시지를 alert 하던 것에서 서버에서 온 오류 message 를 출력하도록 수정
> fix: 오류 메시지 수정(#208)
